Repository gomint/gomint, pull requests merged in 2020-11, with the labels that each got.

#660 Add day cycle
  gomint-api/src/main/java/io/gomint/inventory/item/ItemEnchantable.java
  gomint-api/src/main/java/io/gomint/math/MathUtils.java
  gomint-api/src/main/java/io/gomint/world/Gamerule.java
  gomint-api/src/main/java/io/gomint/world/World.java
  gomint-server/pom.xml
  gomint-server/src/main/java/io/gomint/server/Bootstrap.java
  gomint-server/src/main/java/io/gomint/server/GoMintServer.java
  gomint-server/src/main/java/io/gomint/server/command/CommandManager.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/TimeSetCommand.java
  gomint-server/src/main/java/io/gomint/server/enchant/EnchantmentSelector.java
  gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
  gomint-server/src/main/java/io/gomint/server/jwt/EncryptionRequestForger.java
  gomint-server/src/main/java/io/gomint/server/network/PlayerConnection.java
  gomint-server/src/main/java/io/gomint/server/network/packet/PacketPlayerEnchantmentOptions.java
  gomint-server/src/main/java/io/gomint/server/util/Values.java
  gomint-server/src/main/java/io/gomint/server/world/LevelEvent.java
  gomint-server/src/main/java/io/gomint/server/world/WorldAdapter.java
  gomint-server/src/main/java/io/gomint/server/world/leveldb/LevelDBWorldAdapter.java
  gomint-test-plugin/src/main/java/io/gomint/testplugin/scoreboard/DebugScoreboard.java
Labels: feature

#661 Add Minty manifest to source root
  .mintyfile.yml
Labels: feature

#665 Fix item reading and writing in tile entities
  gomint-server/src/main/java/io/gomint/server/entity/component/AbstractTileEntityComponent.java
  gomint-server/src/main/java/io/gomint/server/entity/component/BlockIdentifierComponent.java
  gomint-server/src/main/java/io/gomint/server/entity/component/InventoryComponent.java
  gomint-server/src/main/java/io/gomint/server/entity/component/ItemComponent.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/BarrelTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/ChestTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/DispenserTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/DropperTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/FlowerPotTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/HopperTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/ItemFrameTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/JukeboxTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/ShulkerBoxTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/TileEntity.java
Labels: bug

#667 Implement vanilla gen 1.16.100
  gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
  gomint-server/src/main/java/io/gomint/server/network/packet/PacketResourcePackStack.java
  gomint-server/src/main/java/io/gomint/server/network/packet/PacketStartGame.java
  gomint-server/src/main/java/io/gomint/server/world/generator/vanilla/VanillaGeneratorImpl.java
  gomint-server/src/main/java/io/gomint/server/world/generator/vanilla/client/Client.java
Labels: bug

#668 API refactor, stabilize for glazed terracota
  check/src/main/java/io/gomint/check/ItemCombiner.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemBlackGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemBlueGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemBrownGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemCyanGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemGrayGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemGreenGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemLightBlueGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemLimeGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemMagentaGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemOrangeGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemPinkGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemPurpleGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemRedGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemSilverGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemType.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemWhiteGlazedTerracotta.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemYellowGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/entity/Entity.java
  gomint-server/src/main/java/io/gomint/server/entity/passive/EntityHuman.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemBlackGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemBlueGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemBrownGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemCyanGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemGrayGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemGreenGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemLightBlueGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemLimeGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemMagentaGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemOrangeGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPinkGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPurpleGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemRedGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemSilverGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemWhiteGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemYellowGlazedTerracotta.java
  gomint-server/src/main/java/io/gomint/server/network/PostProcessWorker.java
  gomint-server/src/main/java/io/gomint/server/network/packet/PacketEntityRelativeMovement.java
  gomint-server/src/main/java/io/gomint/server/world/EntityManager.java
  gomint-server/src/main/java/io/gomint/server/world/leveldb/LevelDBWorldAdapter.java
Labels: feature, reviewing

#670 Fix NPE in knows chunk
  gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
  gomint-server/src/main/java/io/gomint/server/world/EntitySpawner.java
Labels: bug

#672 Fix leak on disconnected players
  gomint-server/src/main/java/io/gomint/server/network/PlayerConnection.java
  gomint-server/src/main/java/io/gomint/server/world/generator/vanilla/VanillaGeneratorImpl.java
  gomint-server/src/main/java/io/gomint/server/world/generator/vanilla/client/Client.java
  gomint-server/src/main/resources/log4j2.xml
Labels: bug

#673 Add enchantment was not int, it was short which forces plugin developers to cast
  gomint-api/src/main/java/io/gomint/inventory/item/ItemStack.java
  gomint-server/pom.xml
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemStack.java
Labels: bug
