Repository gomint/gomint, pull requests merged in 2020-09, with the labels that each got.

#571 Add basic release drafter config
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature

#572 Add merge bot
  .github/workflows/merge-bot.yml
Labels: feature, merge

#573 Add V4 logo assets to repository
  .github/ASSETS/avatar/gomint-avatar-circle.png
  .github/ASSETS/avatar/gomint-avatar-circle.svg
  .github/ASSETS/avatar/gomint-avatar-square.png
  .github/ASSETS/avatar/gomint-avatar-square.svg
  .github/ASSETS/gomint-banner.png
  .github/ASSETS/promo/colored/gomint-promo-powered-colored-left-black.png
  .github/ASSETS/promo/colored/gomint-promo-powered-colored-left-black.svg
  .github/ASSETS/promo/colored/gomint-promo-powered-colored-left-white.png
  .github/ASSETS/promo/colored/gomint-promo-powered-colored-left-white.svg
  .github/ASSETS/promo/colored/gomint-promo-powered-colored-right-black.png
  .github/ASSETS/promo/colored/gomint-promo-powered-colored-right-black.svg
  .github/ASSETS/promo/colored/gomint-promo-powered-colored-right-white.png
  .github/ASSETS/promo/colored/gomint-promo-powered-colored-right-white.svg
  .github/ASSETS/promo/mono/gomint-promo-powered-left-black.png
  .github/ASSETS/promo/mono/gomint-promo-powered-left-black.svg
  .github/ASSETS/promo/mono/gomint-promo-powered-left-white.png
  .github/ASSETS/promo/mono/gomint-promo-powered-left-white.svg
  .github/ASSETS/promo/mono/gomint-promo-powered-right-black.png
  .github/ASSETS/promo/mono/gomint-promo-powered-right-black.svg
  .github/ASSETS/promo/mono/gomint-promo-powered-right-white.png
  .github/ASSETS/promo/mono/gomint-promo-powered-right-white.svg
  .github/ASSETS/pure/gomint-pure-black.png
  .github/ASSETS/pure/gomint-pure-black.svg
  .github/ASSETS/pure/gomint-pure-outline-circle-black.png
  .github/ASSETS/pure/gomint-pure-outline-circle-black.svg
  .github/ASSETS/pure/gomint-pure-outline-circle-white.png
  .github/ASSETS/pure/gomint-pure-outline-circle-white.svg
  .github/ASSETS/pure/gomint-pure-outline-circle.png
  .github/ASSETS/pure/gomint-pure-outline-circle.svg
  .github/ASSETS/pure/gomint-pure-outline-square-black.png
  .github/ASSETS/pure/gomint-pure-outline-square-black.svg
  .github/ASSETS/pure/gomint-pure-outline-square-white.png
  .github/ASSETS/pure/gomint-pure-outline-square-white.svg
  .github/ASSETS/pure/gomint-pure-outline-square.png
  .github/ASSETS/pure/gomint-pure-outline-square.svg
  .github/ASSETS/pure/gomint-pure-white.png
  .github/ASSETS/pure/gomint-pure-white.svg
  .github/ASSETS/pure/gomint-pure.png
  .github/ASSETS/pure/gomint-pure.svg
  .github/ASSETS/text/gomint-text-black.png
  .github/ASSETS/text/gomint-text-black.svg
  .github/ASSETS/text/gomint-text-colored-black.png
  .github/ASSETS/text/gomint-text-colored-black.svg
  .github/ASSETS/text/gomint-text-colored-white.png
  .github/ASSETS/text/gomint-text-colored-white.svg
  .github/ASSETS/text/gomint-text-white.png
  .github/ASSETS/text/gomint-text-white.svg
  .github/ASSETS/text/gomint-text.png
  .github/ASSETS/text/gomint-text.svg
Labels: feature, merge

#574 Add sapling and apple drops to leaves breaking
  check/src/main/java/io/gomint/check/CheckMain.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemCrimsonFungus.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemSapling.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemType.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemWarpedFungus.java
  gomint-api/src/main/java/io/gomint/math/MathUtils.java
  gomint-api/src/main/java/io/gomint/world/block/BlockCrimsonFungus.java
  gomint-api/src/main/java/io/gomint/world/block/BlockSapling.java
  gomint-api/src/main/java/io/gomint/world/block/BlockType.java
  gomint-api/src/main/java/io/gomint/world/block/BlockWarpedFungus.java
  gomint-server/src/main/java/io/gomint/server/enchant/Enchantment.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemCrimsonFungus.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemSapling.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemWarpedFungus.java
  gomint-server/src/main/java/io/gomint/server/world/block/CrimsonFungus.java
  gomint-server/src/main/java/io/gomint/server/world/block/Leaves.java
  gomint-server/src/main/java/io/gomint/server/world/block/Sapling.java
  gomint-server/src/main/java/io/gomint/server/world/block/WarpedFungus.java
Labels: bug, merge

#575 Remove freestanding shapes left and right
  .github/ASSETS/gomint-banner.png
Labels: feature, merge

#578 Fix not working eating
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketInventoryTransactionHandler.java
Labels: bug, merge

#577 Ice breaking not giving water
  gomint-server/src/main/java/io/gomint/server/world/WorldAdapter.java
  gomint-server/src/main/java/io/gomint/server/world/block/Block.java
  gomint-server/src/main/java/io/gomint/server/world/block/Ice.java
Labels: bug, merge

#576 Add double chest pairing
  generator/src/main/java/io/gomint/generator/GeneratorMain.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemBlackstoneSlab.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemType.java
  gomint-server/src/main/java/io/gomint/server/crafting/ShapedRecipe.java
  gomint-server/src/main/java/io/gomint/server/crafting/ShapelessRecipe.java
  gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/ChestTileEntity.java
  gomint-server/src/main/java/io/gomint/server/inventory/ArmorInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/ContainerInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/CraftingInputInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/CreativeInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/CursorInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/DoubleChestInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/Inventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/OffhandInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/PlayerInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemBlackstoneSlab.java
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketBlockPickRequestHandler.java
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketCraftingEventHandler.java
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketInventoryTransactionHandler.java
  gomint-server/src/main/java/io/gomint/server/network/packet/PacketCreativeContent.java
  gomint-server/src/main/java/io/gomint/server/world/block/BlastFurnace.java
  gomint-server/src/main/java/io/gomint/server/world/block/ChestBase.java
  gomint-server/src/main/java/io/gomint/server/world/block/Furnace.java
  gomint-test-plugin/src/main/java/io/gomint/testplugin/TestPlugin.java
Labels: feature, merge

#581 Change merge bot to use merge commits
  .github/workflows/merge-bot.yml
Labels: bug, merge

#584 Add GoMinty token
  .github/workflows/merge-bot.yml
Labels: bug, merge

#587 Eating works now
  gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
  gomint-server/src/main/java/io/gomint/server/entity/passive/EntityHuman.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemCookedChicken.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemFood.java
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketEntityEventHandler.java
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketInventoryTransactionHandler.java
Labels: bug, merge

#590 Fix shooting bows. Fixes #589
  gomint-server/src/main/java/io/gomint/server/entity/projectile/EntityProjectile.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemBow.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemCrossbow.java
  gomint-server/src/main/java/io/gomint/server/network/packet/PacketInventoryTransaction.java
Labels: bug, merge

#591 Add tnt type. Fix item TNT selecting the wrong block variant.
  gomint-api/src/main/java/io/gomint/inventory/item/ItemTNT.java
  gomint-api/src/main/java/io/gomint/world/block/BlockTNT.java
  gomint-api/src/main/java/io/gomint/world/block/data/TNTType.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemTNT.java
  gomint-server/src/main/java/io/gomint/server/world/block/TNT.java
Labels: bug, merge

#596 Fix not hardening to obsidian when emptying a bucket of lava into water
  gomint-server/src/main/java/io/gomint/server/world/block/FlowingLava.java
  gomint-server/src/main/java/io/gomint/server/world/block/StationaryLava.java
Labels: bug, merge

#599 Fix bark on all side tree generation. Fixes #595
  gomint-api/src/main/java/io/gomint/world/generator/object/BirchTree.java
  gomint-api/src/main/java/io/gomint/world/generator/object/OakTree.java
Labels: bug, merge

#601 Fix fallables not falling when they should
  gomint-server/src/main/java/io/gomint/server/entity/passive/EntityFallingBlock.java
  gomint-server/src/main/java/io/gomint/server/entity/passive/EntityXPOrb.java
  gomint-server/src/main/java/io/gomint/server/world/WorldAdapter.java
  gomint-server/src/main/java/io/gomint/server/world/block/Bed.java
  gomint-server/src/main/java/io/gomint/server/world/block/Block.java
  gomint-server/src/main/java/io/gomint/server/world/block/Blocks.java
  gomint-server/src/main/java/io/gomint/server/world/block/ChestBase.java
  gomint-server/src/main/java/io/gomint/server/world/block/Fallable.java
  gomint-server/src/main/java/io/gomint/server/world/block/IronDoor.java
  gomint-server/src/main/java/io/gomint/server/world/block/WoodenDoor.java
Labels: bug, merge

#603 Fix math errors in chunk loading and general applications
  gomint-api/pom.xml
  gomint-api/src/main/java/io/gomint/math/MathUtils.java
  gomint-api/src/main/java/module-info.java
Labels: bug, merge, reviewing

#606 Re-add proxyCount to EventProxy className
  gomint-server/src/main/java/io/gomint/server/event/EventHandlerMethod.java
Labels: bug, merge

#607 Add new workflow for branches and PRs
  .github/workflows/java-compile.yml
  .github/workflows/maven.yml
Labels: feature, merge

#612 Remove old xbox auth to avoid confusion
  gomint-server/src/main/java/io/gomint/server/config/ServerConfig.java
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketLoginHandler.java
Labels: bug

#613 Add no key support (for JWT validation)
  gomint-server/src/main/java/io/gomint/server/jwt/MojangChainValidator.java
  gomint-server/src/main/java/io/gomint/server/network/EncryptionKeyFactory.java
Labels: feature

#614 Add support for swapping out the permission manager of a player
  gomint-api/src/main/java/io/gomint/entity/EntityPlayer.java
  gomint-api/src/main/java/io/gomint/permission/PermissionManager.java
  gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
Labels: feature

#619 Check for correct plugin even for event listeners
  gomint-server/src/main/java/io/gomint/server/plugin/PluginClassloader.java
  gomint-server/src/main/java/io/gomint/server/util/SecurityManagerCallerDetector.java
Labels: bug

#622 Fix plugin threads not returning correct plugin class
  gomint-server/src/main/java/io/gomint/server/util/SecurityManagerCallerDetector.java
Labels: bug

#621 Delete cleanup.txt just for testing if tip works correctly
  cleanup.txt
Labels: bug

#608 Add shared class between BlockSignNormal and BlockWallSign
  gomint-api/src/main/java/io/gomint/event/world/SignChangeTextEvent.java
  gomint-api/src/main/java/io/gomint/world/block/BlockSign.java
  gomint-api/src/main/java/io/gomint/world/block/BlockStandingSign.java
  gomint-api/src/main/java/io/gomint/world/block/BlockWallSign.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/SignTileEntity.java
  gomint-server/src/main/java/io/gomint/server/world/block/Sign.java
  gomint-server/src/main/java/io/gomint/server/world/block/StandingSign.java
  gomint-server/src/main/java/io/gomint/server/world/block/WallSign.java
Labels: feature, merge

#623 Fix not reading stdin when jLine failed. Fixes #616
  gomint-server/src/main/java/io/gomint/server/GoMintServer.java
  gomint-server/src/main/java/io/gomint/server/logging/TerminalConsoleAppender.java
Labels: bug

#624 Create static methods for creating a CommandOutput to replace constructor call
  gomint-api/src/main/java/io/gomint/command/CommandOutput.java
  gomint-server/src/main/java/io/gomint/server/command/CommandManager.java
  gomint-server/src/main/java/io/gomint/server/command/SubCommand.java
  gomint-server/src/main/java/io/gomint/server/command/gomint/KickCommand.java
  gomint-server/src/main/java/io/gomint/server/command/gomint/PluginsCommand.java
  gomint-server/src/main/java/io/gomint/server/command/gomint/StopCommand.java
  gomint-server/src/main/java/io/gomint/server/command/gomint/VersionCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/DeopCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/DifficultyCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/GamemodeCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/ListCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/MeCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/OpCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/SayCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/SetWorldSpawnCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/SpawnPointCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/TPCommand.java
  gomint-server/src/main/java/io/gomint/server/command/vanilla/TellCommand.java
  gomint-test-plugin/src/main/java/io/gomint/testplugin/command/TestCommand.java
Labels: feature

#626 Fix rounding errors and deprecate location getter in block
  gomint-api/src/main/java/io/gomint/math/BlockPosition.java
  gomint-api/src/main/java/io/gomint/math/Location.java
  gomint-api/src/main/java/io/gomint/math/Vector.java
  gomint-api/src/main/java/io/gomint/world/World.java
  gomint-api/src/main/java/io/gomint/world/block/Block.java
  gomint-server/src/main/java/io/gomint/server/entity/Entity.java
  gomint-server/src/main/java/io/gomint/server/entity/ai/AIPassiveIdleMovement.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/BarrelTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/ChestTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/DispenserTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/DropperTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/EnderChestTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/HopperTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/NoteblockTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/ShulkerBoxTileEntity.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/TileEntity.java
  gomint-server/src/main/java/io/gomint/server/inventory/ContainerInventory.java
  gomint-server/src/main/java/io/gomint/server/inventory/EnchantmentTableInventory.java
  gomint-server/src/main/java/io/gomint/server/util/StatefulBlockSearcher.java
  gomint-server/src/main/java/io/gomint/server/world/ChunkAdapter.java
  gomint-server/src/main/java/io/gomint/server/world/ChunkSlice.java
  gomint-server/src/main/java/io/gomint/server/world/Explosion.java
  gomint-server/src/main/java/io/gomint/server/world/WorldAdapter.java
  gomint-server/src/main/java/io/gomint/server/world/block/Block.java
  gomint-server/src/main/java/io/gomint/server/world/block/Blocks.java
  gomint-server/src/main/java/io/gomint/server/world/block/Door.java
  gomint-server/src/main/java/io/gomint/server/world/block/DragonEgg.java
  gomint-server/src/main/java/io/gomint/server/world/block/Farmland.java
  gomint-server/src/main/java/io/gomint/server/world/block/Liquid.java
  gomint-server/src/main/java/io/gomint/server/world/block/Vines.java
Labels: bug

#627 Add default profiler to startup
  release/start.cmd
  release/start.sh
Labels: feature

#628 Also add JMX to JVM startup not just JDWP
  release/start.sh
Labels: feature

#629 Forgot to enable JMX
  release/start.sh
Labels: bug

#631 Fix stdin not attached leading to 100% cpu usage
  gomint-server/src/main/java/io/gomint/server/GoMintServer.java
Labels: bug

#630 Fix cauldron default state
  gomint-api/src/main/java/io/gomint/world/block/BlockCauldron.java
  gomint-api/src/main/java/io/gomint/world/block/BlockLiquid.java
  gomint-api/src/main/java/io/gomint/world/block/data/LiquidType.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemCauldron.java
  gomint-server/src/main/java/io/gomint/server/world/block/Cauldron.java
  gomint-server/src/main/java/io/gomint/server/world/block/Liquid.java
Labels: bug

#632 Add wall connection and pole API / logic
  gomint-api/src/main/java/io/gomint/inventory/item/ItemBlackstoneWall.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemCobblestoneWall.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemPolishedBlackstoneBrickWall.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemPolishedBlackstoneWall.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemType.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemWall.java
  gomint-api/src/main/java/io/gomint/world/block/BlockWall.java
  gomint-api/src/main/java/io/gomint/world/block/data/ConnectionType.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemBlackstoneWall.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemCobblestoneWall.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPolishedBlackstoneBrickWall.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemPolishedBlackstoneWall.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemWall.java
  gomint-server/src/main/java/io/gomint/server/world/block/Wall.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/BlockState.java
Labels: feature

#633 Fix sapling placing on each other
  gomint-server/src/main/java/io/gomint/server/world/block/NetherWart.java
  gomint-server/src/main/java/io/gomint/server/world/block/Sapling.java
Labels: bug

#634 Expose player address to API users
  gomint-api/src/main/java/io/gomint/entity/EntityPlayer.java
  gomint-server/src/main/java/io/gomint/server/entity/EntityPlayer.java
Labels: feature

#636 Fix block rotation and add source and javadoc to API artifact
  gomint-api/pom.xml
  gomint-api/src/main/java/io/gomint/command/Command.java
  gomint-api/src/main/java/io/gomint/entity/EntityLiving.java
  gomint-api/src/main/java/io/gomint/event/EventHandler.java
  gomint-api/src/main/java/io/gomint/gui/CustomForm.java
  gomint-api/src/main/java/io/gomint/i18n/localization/ResourceManager.java
  gomint-api/src/main/java/io/gomint/inventory/item/ItemStack.java
  gomint-api/src/main/java/io/gomint/plugin/Plugin.java
  gomint-api/src/main/java/io/gomint/world/block/BlockDoor.java
  gomint-api/src/main/java/io/gomint/world/block/data/HingeSide.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemWoodenDoor.java
  gomint-server/src/main/java/io/gomint/server/util/Bearing.java
  gomint-server/src/main/java/io/gomint/server/world/block/Door.java
  gomint-server/src/main/java/io/gomint/server/world/block/Stair.java
  gomint-server/src/main/java/io/gomint/server/world/block/Torch.java
  gomint-server/src/main/java/io/gomint/server/world/block/WoodenDoor.java
Labels: bug

#637 Fix signed varint encoding with jRaknet update
  gomint-server/pom.xml
Labels: bug

#638 Change minecraft version to 1.16.40
  gomint-api/src/main/java/io/gomint/ChatColor.java
  gomint-server/src/main/java/io/gomint/server/GoMintServer.java
  gomint-server/src/main/java/io/gomint/server/command/gomint/PluginsCommand.java
  gomint-server/src/main/java/io/gomint/server/network/Protocol.java
Labels: feature

#639 Fixed wrong twitter url in readme
  README.md
Labels: bug

#640 Remove the profiler again, we should implement some custom params
  release/start.sh
Labels: bug

#641 Remove latest release, it collides with the release drafter
  .github/workflows/build-and-deploy.yml
Labels: bug

#642 Add s3 upload for latest
  .github/workflows/build-and-deploy.yml
Labels: feature

#643 Next s3 upload action :D
  .github/workflows/build-and-deploy.yml
Labels: bug

#644 Fix NPE from wall type mapping
  gomint-server/src/main/java/io/gomint/server/world/block/Wall.java
  unnamed.patch
Labels: bug

#645 Fix projectile look and motion updates
  gomint-server/src/main/java/io/gomint/server/entity/Entity.java
  gomint-server/src/main/java/io/gomint/server/entity/projectile/EntityArrow.java
  gomint-server/src/main/java/io/gomint/server/entity/projectile/EntityEnderpearl.java
  gomint-server/src/main/java/io/gomint/server/entity/projectile/EntityExpBottle.java
  gomint-server/src/main/java/io/gomint/server/entity/projectile/EntityFishingHook.java
  gomint-server/src/main/java/io/gomint/server/entity/projectile/EntityProjectile.java
  gomint-server/src/main/java/io/gomint/server/entity/projectile/EntitySnowball.java
  gomint-server/src/main/java/io/gomint/server/entity/projectile/EntityThrowable.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemFishingRod.java
  gomint-server/src/main/java/io/gomint/server/world/block/Trapdoor.java
Labels: bug

#647 Fixed liquids not decaying if they flow downwards
  gomint-server/src/main/java/io/gomint/server/entity/pathfinding/PathfindingEngine.java
  gomint-server/src/main/java/io/gomint/server/world/WorldAdapter.java
  gomint-server/src/main/java/io/gomint/server/world/block/Block.java
  gomint-server/src/main/java/io/gomint/server/world/block/Blocks.java
  gomint-server/src/main/java/io/gomint/server/world/block/Liquid.java
  unnamed.patch
Labels: bug

#650 fix me command
  gomint-server/src/main/java/io/gomint/server/command/vanilla/MeCommand.java
Labels: bug

#651 Fix not selecting aliased commands
  gomint-server/src/main/java/io/gomint/server/command/CommandManager.java
  gomint-test-plugin/src/main/java/io/gomint/testplugin/command/TestCommand.java
Labels: bug

#652 Allow plugin module read access to dependant plugins which does not contain a module info
  gomint-api/pom.xml
  gomint-server/src/main/java/io/gomint/server/plugin/PluginMeta.java
  gomint-server/src/main/java/io/gomint/server/plugin/SimplePluginManager.java
Labels: feature, reviewing
