Repository gomint/gomint, pull requests merged in 2021-01, with the labels that each got.

#685 Add ARM support (currently only 32bit [for PI])
  gomint-server/pom.xml
  gomint-server/src/main/java/io/gomint/server/Bootstrap.java
Labels: feature

#686 Remove watchdog from sentry
  gomint-server/src/main/java/io/gomint/server/util/Watchdog.java
  release/start.cmd
  release/start.sh
Labels: feature

#689 Update readme to newer standards
  .github/ASSETS/gomint-banner.png
  .github/ASSETS/gomint-logo-with-text.svg
  .github/ASSETS/logo_discord.png
  .github/ASSETS/logo_twitter.png
  .mintyfile.yml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
Labels: feature, optimization

#695 Fix crafting input slot offset
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketItemStackRequestHandler.java
  gomint-server/src/main/java/io/gomint/server/util/Values.java
Labels: bug

#704 Add refactor to the draft release
  .github/release-drafter.yml
Labels: feature

#703 Fix item NPE for the jukebox
  gomint-server/src/main/java/io/gomint/server/entity/component/AbstractTileEntityComponent.java
  gomint-server/src/main/java/io/gomint/server/entity/component/ItemComponent.java
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/JukeboxTileEntity.java
  gomint-server/src/main/java/io/gomint/server/inventory/item/Items.java
  gomint-server/src/main/java/io/gomint/server/registry/StringRegistry.java
  gomint-server/src/main/java/io/gomint/server/world/block/Beetroot.java
  gomint-server/src/main/java/io/gomint/server/world/block/Carrots.java
  gomint-server/src/main/java/io/gomint/server/world/block/Crops.java
  gomint-server/src/main/java/io/gomint/server/world/block/Potato.java
Labels: bug

#707 Add setup instructions for IDE as developer setup
  README.md
Labels: feature

#708 Fix Log rotation
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemLog.java
  gomint-server/src/main/java/io/gomint/server/world/block/Log.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/AxisBlockState.java
Labels: bug

#710 fix some bug on block placed
  gomint-server/src/main/java/io/gomint/server/inventory/item/ItemDarkOakTrapdoor.java
  gomint-server/src/main/java/io/gomint/server/world/block/Bed.java
  gomint-server/src/main/java/io/gomint/server/world/block/BeeHive.java
  gomint-server/src/main/java/io/gomint/server/world/block/Block.java
  gomint-server/src/main/java/io/gomint/server/world/block/Blocks.java
  gomint-server/src/main/java/io/gomint/server/world/block/Button.java
  gomint-server/src/main/java/io/gomint/server/world/block/Cake.java
  gomint-server/src/main/java/io/gomint/server/world/block/Cauldron.java
  gomint-server/src/main/java/io/gomint/server/world/block/ChestBase.java
  gomint-server/src/main/java/io/gomint/server/world/block/CommandBlock.java
  gomint-server/src/main/java/io/gomint/server/world/block/Door.java
  gomint-server/src/main/java/io/gomint/server/world/block/Flower.java
  gomint-server/src/main/java/io/gomint/server/world/block/Growable.java
  gomint-server/src/main/java/io/gomint/server/world/block/Jigsaw.java
  gomint-server/src/main/java/io/gomint/server/world/block/LilyPad.java
  gomint-server/src/main/java/io/gomint/server/world/block/Liquid.java
  gomint-server/src/main/java/io/gomint/server/world/block/Log.java
  gomint-server/src/main/java/io/gomint/server/world/block/NetherWart.java
  gomint-server/src/main/java/io/gomint/server/world/block/Pumpkin.java
  gomint-server/src/main/java/io/gomint/server/world/block/RailBase.java
  gomint-server/src/main/java/io/gomint/server/world/block/Sapling.java
  gomint-server/src/main/java/io/gomint/server/world/block/Skull.java
  gomint-server/src/main/java/io/gomint/server/world/block/Slab.java
  gomint-server/src/main/java/io/gomint/server/world/block/SoulCampfire.java
  gomint-server/src/main/java/io/gomint/server/world/block/SoulTorch.java
  gomint-server/src/main/java/io/gomint/server/world/block/Stair.java
  gomint-server/src/main/java/io/gomint/server/world/block/TNT.java
  gomint-server/src/main/java/io/gomint/server/world/block/Torch.java
  gomint-server/src/main/java/io/gomint/server/world/block/Trapdoor.java
  gomint-server/src/main/java/io/gomint/server/world/block/Vines.java
  gomint-server/src/main/java/io/gomint/server/world/block/Wall.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/AttachingBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/AxisBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/BlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/BlockfaceBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/BlockfaceFromPlayerBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/BooleanBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/CrossDirectionBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/DirectValueBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/DirectionBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/EnumBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/HalfBlockState.java
  gomint-server/src/main/java/io/gomint/server/world/block/state/ProgressBlockState.java
Labels: bug

#712 Add plugin-parent and plugin-archetype so once we hit maven central w…
  plugin-archetype/pom.xml
  plugin-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
  plugin-archetype/src/main/resources/archetype-resources/pom.xml
  plugin-archetype/src/main/resources/archetype-resources/src/main/java/PluginEntry.java
  plugin-parent/pom.xml
Labels: feature

#714 Fix configuration error message referring to wrong file name
  gomint-server/src/main/java/io/gomint/server/GoMintServer.java
Labels: typo

#718 Add support for new MAC M1 (aarch64 on darwin)
  gomint-server/pom.xml
  gomint-server/src/main/java/io/gomint/server/world/leveldb/LevelDBWorldAdapter.java
Labels: feature

#720 According to JEPS-261 (https://openjdk.java.net/jeps/261) a container…
  README.md
  release/start.cmd
  release/start.sh
Labels: bug

#721 Fix AIOOB when using the small crafting window. This fixes #717
  gomint-server/src/main/java/io/gomint/server/network/handler/PacketItemStackRequestHandler.java
  gomint-server/src/main/java/io/gomint/server/util/Values.java
Labels: bug

#722 Add hint that you need java 11 to start gomint
  README.md
Labels: refactoring

#723 Fix that itemstacks don't persist their NBT
  gomint-server/src/main/java/io/gomint/server/entity/AttributeInstance.java
  gomint-server/src/main/java/io/gomint/server/inventory/Inventory.java
  gomint-server/src/main/java/io/gomint/server/world/leveldb/LevelDBChunkAdapter.java
  gomint-server/src/main/java/io/gomint/server/world/leveldb/LevelDBWorldAdapter.java
Labels: bug

#724 Fix permission manager not checking correctly due to internal string usage
  gomint-server/src/main/java/io/gomint/server/permission/PermissionGroup.java
  gomint-server/src/main/java/io/gomint/server/permission/PermissionManager.java
  gomint-server/src/test/java/io/gomint/server/test/permission/PermissionTest.java
Labels: bug

#730 Fix loading signs, add missing blocks.
  gomint-api/src/main/java/io/gomint/world/block/BlockCartographyTable.java
  gomint-api/src/main/java/io/gomint/world/block/BlockConduit.java
  gomint-api/src/main/java/io/gomint/world/block/BlockDriedKelp.java
  gomint-api/src/main/java/io/gomint/world/block/BlockPolishedBlackstoneButton.java
  gomint-api/src/main/java/io/gomint/world/block/BlockPolishedBlackstonePressurePlate.java
  gomint-api/src/main/java/io/gomint/world/block/BlockSmithingTable.java
  gomint-api/src/main/java/io/gomint/world/block/BlockType.java
  gomint-server/pom.xml
  gomint-server/src/main/java/io/gomint/server/entity/tileentity/SignTileEntity.java
  gomint-server/src/main/java/io/gomint/server/world/block/CartographyTable.java
  gomint-server/src/main/java/io/gomint/server/world/block/Conduit.java
  gomint-server/src/main/java/io/gomint/server/world/block/DriedKelp.java
  gomint-server/src/main/java/io/gomint/server/world/block/PolishedBlackstoneButton.java
  gomint-server/src/main/java/io/gomint/server/world/block/PolishedBlackstonePressurePlate.java
  gomint-server/src/main/java/io/gomint/server/world/block/ShroomLight.java
  gomint-server/src/main/java/io/gomint/server/world/block/Sign.java
  gomint-server/src/main/java/io/gomint/server/world/block/SmithingTable.java
  gomint-server/src/main/java/io/gomint/server/world/block/Stonecutter.java
  gomint-server/src/main/java/io/gomint/server/world/block/StructureVoid.java
  gomint-server/src/main/java/io/gomint/server/world/block/Unknown.java
  gomint-server/src/main/java/io/gomint/server/world/block/helper/ToolPresets.java
  gomint-server/src/main/resources/assets.dat
  gomint-server/src/test/java/io/gomint/server/test/entity/tile/SignTileTest.java
Labels: api changes, bug
